"""teste-1_creat_at

Revision ID: 14873971dc2d
Revises: 3640d99f5b2b
Create Date: 2025-08-12 21:46:01.818559

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14873971dc2d'
down_revision: Union[str, Sequence[str], None] = '3640d99f5b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('usuario', 'creat_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('creat_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'created_at')
    # ### end Alembic commands ###
