"""teste-2_creat_at

Revision ID: c62aeffdb832
Revises: 14873971dc2d
Create Date: 2025-08-12 21:47:25.114029

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c62aeffdb832'
down_revision: Union[str, Sequence[str], None] = '14873971dc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
