"""retirando unidade de medida dos produtos

Revision ID: e0b446627458
Revises: 603ebc76ee72
Create Date: 2025-08-18 22:20:20.041425

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0b446627458'
down_revision: Union[str, Sequence[str], None] = '603ebc76ee72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('produtos_id_key'), 'produtos', type_='unique')
    op.drop_column('produtos', 'unidade_medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('unidade_medida', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('produtos_id_key'), 'produtos', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
