"""correção de args_id

Revision ID: 3640d99f5b2b
Revises: 1b9ed8f71577
Create Date: 2025-08-12 21:31:16.141866

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3640d99f5b2b'
down_revision: Union[str, Sequence[str], None] = '1b9ed8f71577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_id_key'), 'usuario', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuario_id_key'), 'usuario', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
