"""retirando tipo_user

Revision ID: 4d2d2e8b07c2
Revises: c8bd408c4903
Create Date: 2025-08-12 18:50:51.300255

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d2d2e8b07c2'
down_revision: Union[str, Sequence[str], None] = 'c8bd408c4903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tipo_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('tipo_usuario', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
