"""add_autoincremento

Revision ID: c8bd408c4903
Revises: 9059656b3762
Create Date: 2025-08-12 18:17:10.996049

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8bd408c4903'
down_revision: Union[str, Sequence[str], None] = '9059656b3762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'produtos', ['id'])
    op.create_unique_constraint(None, 'usuario', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'produtos', type_='unique')
    # ### end Alembic commands ###
